//===----------------------------------------------------------------------===//
//
//  HandlerService.swift
//  StarlightCore
//
//  `HandlerService<T0, T1, …>` — the `Service<Request>` adapter
//  around a closure of N extractor parameters. Direct port of the
//  `#[async_trait] impl Handler<(T0, T1, …), S, B> for F` blanket
//  impl in axum-core.
//
//  axum uses a macro to generate one impl per arity (up to 16).
//  We do the same in Swift: one `HandlerService` struct per arity,
//  generated by hand for the common cases (0, 1, 2, 3 extractors).
//  If you need more, add another `HandlerService` struct.
//
//===----------------------------------------------------------------------===//

import Foundation
import HTTP
import Pylon

/// Errors surfaced by the handler dispatcher when extraction fails.
///
/// `ExtractionRejection` thrown by an extractor is rebound here so
/// the router can distinguish "extractor said no" (4xx) from
/// "extractor panicked / IO failed" (5xx).
public enum HandlerError: Error, Sendable {
    /// Body was already consumed by a prior body-extractor in the
    /// chain. Should be unreachable — handler adapters enforce the
    /// "at most one body extractor, last argument" rule.
    case bodyAlreadyConsumed
    /// Rejection from an extractor — already wrapped in its
    /// `intoResponse()` form so the dispatcher just returns it.
    case rejection(HTTP.Response)
}

/// Zero-extractor handler — `() -> IntoResponse`.
/// axum analogue: `impl Handler<(), S> for F`.
public struct HandlerService0<Fn, S, Out>: Sendable
where Fn: Sendable, S: Sendable, Out: IntoResponse {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService0: Service {

    public func call(_ request: consuming HTTP.Request) async throws -> HTTP.Response {
        try await f(state).intoResponse()
    }
}

extension HandlerService0: Handler where S == NoState {}

/// One-extractor handler — `(E0) -> IntoResponse`.
public struct HandlerService1<E0, Fn, S, Out>: Sendable
where E0: FromRequestParts, Fn: Sendable, S: Sendable, Out: IntoResponse,
      E0.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService1: Service {

    public func call(_ request: consuming HTTP.Request) async throws -> HTTP.Response {
        var parts = RequestParts(request)
        let e0: E0
        do {
            e0 = try await E0.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        return try await f(e0, state).intoResponse()
    }
}

/// Two-extractor handler — `(E0, E1) -> IntoResponse`.
/// `E0` is `FromRequestParts`, `E1` may be `FromRequest` (body-consuming).
public struct HandlerService2<E0, E1, Fn, S, Out>: Sendable
where E0: FromRequestParts, E1: FromRequest, Fn: Sendable, S: Sendable,
      Out: IntoResponse, E0.State == S, E1.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, E1, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, E1, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService2: Service {

    public func call(_ request: consuming HTTP.Request) async throws -> HTTP.Response {
        var parts = RequestParts(request)
        let e0: E0
        do {
            e0 = try await E0.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        guard let remainingBody = parts.body else {
            throw HandlerError.bodyAlreadyConsumed
        }
        let remaining = HTTP.Request(
            method: parts.method, uri: parts.uri, version: parts.version,
            headers: parts.headers, body: remainingBody,
            extensions: parts.extensions
        )
        let e1: E1
        do {
            e1 = try await E1.fromRequest(remaining, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        return try await f(e0, e1, state).intoResponse()
    }
}

/// Three-extractor handler — `(E0, E1, E2) -> IntoResponse`.
/// `E0`, `E1` are `FromRequestParts`; `E2` may be `FromRequest`.
public struct HandlerService3<E0, E1, E2, Fn, S, Out>: Sendable
where E0: FromRequestParts, E1: FromRequestParts, E2: FromRequest,
      Fn: Sendable, S: Sendable, Out: IntoResponse,
      E0.State == S, E1.State == S, E2.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, E1, E2, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, E1, E2, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService3: Service {

    public func call(_ request: consuming HTTP.Request) async throws -> HTTP.Response {
        var parts = RequestParts(request)
        let e0: E0
        let e1: E1
        do {
            e0 = try await E0.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        do {
            e1 = try await E1.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        guard let remainingBody = parts.body else {
            throw HandlerError.bodyAlreadyConsumed
        }
        let remaining = HTTP.Request(
            method: parts.method, uri: parts.uri, version: parts.version,
            headers: parts.headers, body: remainingBody,
            extensions: parts.extensions
        )
        let e2: E2
        do {
            e2 = try await E2.fromRequest(remaining, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        return try await f(e0, e1, e2, state).intoResponse()
    }
}

// MARK: - HandlerService4 (4 extractors)

/// Four-extractor handler — `(E0, E1, E2, E3) -> IntoResponse`.
/// `E0-E2` are `FromRequestParts`; `E3` may be `FromRequest`.
public struct HandlerService4<E0, E1, E2, E3, Fn, S, Out>: Sendable
where E0: FromRequestParts, E1: FromRequestParts, E2: FromRequestParts, E3: FromRequest,
      Fn: Sendable, S: Sendable, Out: IntoResponse,
      E0.State == S, E1.State == S, E2.State == S, E3.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, E1, E2, E3, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, E1, E2, E3, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService4: Service {
    public func call(_ request: consuming HTTP.Request) async throws -> HTTP.Response {
        var parts = RequestParts(request)
        let e0: E0, e1: E1, e2: E2
        do { e0 = try await E0.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e1 = try await E1.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e2 = try await E2.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        guard let body = parts.body else { throw HandlerError.bodyAlreadyConsumed }
        let req = HTTP.Request(method: parts.method, uri: parts.uri,
            version: parts.version, headers: parts.headers, body: body,
            extensions: parts.extensions)
        let e3: E3
        do { e3 = try await E3.fromRequest(req, state: state) }
        catch let r as ExtractionRejection { return r.response }
        return try await f(e0, e1, e2, e3, state).intoResponse()
    }
}

// MARK: - HandlerService5 (5 extractors)

public struct HandlerService5<E0, E1, E2, E3, E4, Fn, S, Out>: Sendable
where E0: FromRequestParts, E1: FromRequestParts, E2: FromRequestParts, E3: FromRequestParts, E4: FromRequest,
      Fn: Sendable, S: Sendable, Out: IntoResponse,
      E0.State == S, E1.State == S, E2.State == S, E3.State == S, E4.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, E1, E2, E3, E4, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, E1, E2, E3, E4, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService5: Service {
    public func call(_ request: consuming HTTP.Request) async throws -> HTTP.Response {
        var parts = RequestParts(request)
        let e0: E0, e1: E1, e2: E2, e3: E3
        do { e0 = try await E0.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e1 = try await E1.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e2 = try await E2.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e3 = try await E3.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        guard let body = parts.body else { throw HandlerError.bodyAlreadyConsumed }
        let req = HTTP.Request(method: parts.method, uri: parts.uri,
            version: parts.version, headers: parts.headers, body: body,
            extensions: parts.extensions)
        let e4: E4
        do { e4 = try await E4.fromRequest(req, state: state) }
        catch let r as ExtractionRejection { return r.response }
        return try await f(e0, e1, e2, e3, e4, state).intoResponse()
    }
}

// MARK: - HandlerService6 (6 extractors)

public struct HandlerService6<E0, E1, E2, E3, E4, E5, Fn, S, Out>: Sendable
where E0: FromRequestParts, E1: FromRequestParts, E2: FromRequestParts, E3: FromRequestParts, E4: FromRequestParts, E5: FromRequest,
      Fn: Sendable, S: Sendable, Out: IntoResponse,
      E0.State == S, E1.State == S, E2.State == S, E3.State == S, E4.State == S, E5.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, E1, E2, E3, E4, E5, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, E1, E2, E3, E4, E5, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService6: Service {
    public func call(_ request: consuming HTTP.Request) async throws -> HTTP.Response {
        var parts = RequestParts(request)
        let e0: E0, e1: E1, e2: E2, e3: E3, e4: E4
        do { e0 = try await E0.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e1 = try await E1.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e2 = try await E2.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e3 = try await E3.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        do { e4 = try await E4.fromRequestParts(&parts, state: state) }
        catch let r as ExtractionRejection { return r.response }
        guard let body = parts.body else { throw HandlerError.bodyAlreadyConsumed }
        let req = HTTP.Request(method: parts.method, uri: parts.uri,
            version: parts.version, headers: parts.headers, body: body,
            extensions: parts.extensions)
        let e5: E5
        do { e5 = try await E5.fromRequest(req, state: state) }
        catch let r as ExtractionRejection { return r.response }
        return try await f(e0, e1, e2, e3, e4, e5, state).intoResponse()
    }
}
