//===----------------------------------------------------------------------===//
//
//  HandlerService.swift
//  StarlightCore
//
//  `HandlerService<T0, T1, …>` — the `Service<Request>` adapter
//  around a closure of N extractor parameters. Direct port of the
//  `#[async_trait] impl Handler<(T0, T1, …), S, B> for F` blanket
//  impl in axum-core.
//
//  axum uses a macro to generate one impl per arity (up to 16).
//  We do the same in Swift: one `HandlerService` struct per arity,
//  generated by hand for the common cases (0, 1, 2, 3 extractors).
//  If you need more, add another `HandlerService` struct.
//
//===----------------------------------------------------------------------===//

import Foundation
import HTTP
import StarlightTower

/// Errors surfaced by the handler dispatcher when extraction fails.
///
/// `ExtractionRejection` thrown by an extractor is rebound here so
/// the router can distinguish "extractor said no" (4xx) from
/// "extractor panicked / IO failed" (5xx).
public enum HandlerError: Error, Sendable {
    /// Body was already consumed by a prior body-extractor in the
    /// chain. Should be unreachable — handler adapters enforce the
    /// "at most one body extractor, last argument" rule.
    case bodyAlreadyConsumed
    /// Rejection from an extractor — already wrapped in its
    /// `intoResponse()` form so the dispatcher just returns it.
    case rejection(HTTP.Response<Body>)
}

/// Zero-extractor handler — `() -> IntoResponse`.
/// axum analogue: `impl Handler<(), S> for F`.
public struct HandlerService0<Fn, S, Out>: Sendable
where Fn: Sendable, S: Sendable, Out: IntoResponse {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService0: Service {

    public func call(_ request: consuming HTTP.Request<Body>) async throws -> HTTP.Response<Body> {
        try await f(state).intoResponse()
    }
}

extension HandlerService0: Handler where S == NoState {}

/// One-extractor handler — `(E0) -> IntoResponse`.
public struct HandlerService1<E0, Fn, S, Out>: Sendable
where E0: FromRequestParts, Fn: Sendable, S: Sendable, Out: IntoResponse,
      E0.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService1: Service {

    public func call(_ request: consuming HTTP.Request<Body>) async throws -> HTTP.Response<Body> {
        var parts = RequestParts<Body>(request)
        let e0: E0
        do {
            e0 = try await E0.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        return try await f(e0, state).intoResponse()
    }
}

/// Two-extractor handler — `(E0, E1) -> IntoResponse`.
/// `E0` is `FromRequestParts`, `E1` may be `FromRequest` (body-consuming).
public struct HandlerService2<E0, E1, Fn, S, Out>: Sendable
where E0: FromRequestParts, E1: FromRequest, Fn: Sendable, S: Sendable,
      Out: IntoResponse, E0.State == S, E1.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, E1, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, E1, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService2: Service {

    public func call(_ request: consuming HTTP.Request<Body>) async throws -> HTTP.Response<Body> {
        var parts = RequestParts<Body>(request)
        let e0: E0
        do {
            e0 = try await E0.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        guard let remainingBody = parts.body else {
            throw HandlerError.bodyAlreadyConsumed
        }
        let remaining = HTTP.Request<Body>(
            method: parts.method, uri: parts.uri, version: parts.version,
            headers: parts.headers, body: remainingBody,
            extensions: parts.extensions
        )
        let e1: E1
        do {
            e1 = try await E1.fromRequest(remaining, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        return try await f(e0, e1, state).intoResponse()
    }
}

/// Three-extractor handler — `(E0, E1, E2) -> IntoResponse`.
/// `E0`, `E1` are `FromRequestParts`; `E2` may be `FromRequest`.
public struct HandlerService3<E0, E1, E2, Fn, S, Out>: Sendable
where E0: FromRequestParts, E1: FromRequestParts, E2: FromRequest,
      Fn: Sendable, S: Sendable, Out: IntoResponse,
      E0.State == S, E1.State == S, E2.State == S {
    @usableFromInline internal let state: S
    @usableFromInline internal let f: @Sendable (E0, E1, E2, S) async throws -> Out

    @inlinable
    public init(state: S, _ f: @Sendable @escaping (E0, E1, E2, S) async throws -> Out) {
        self.state = state
        self.f = f
    }
}

extension HandlerService3: Service {

    public func call(_ request: consuming HTTP.Request<Body>) async throws -> HTTP.Response<Body> {
        var parts = RequestParts<Body>(request)
        let e0: E0
        let e1: E1
        do {
            e0 = try await E0.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        do {
            e1 = try await E1.fromRequestParts(&parts, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        guard let remainingBody = parts.body else {
            throw HandlerError.bodyAlreadyConsumed
        }
        let remaining = HTTP.Request<Body>(
            method: parts.method, uri: parts.uri, version: parts.version,
            headers: parts.headers, body: remainingBody,
            extensions: parts.extensions
        )
        let e2: E2
        do {
            e2 = try await E2.fromRequest(remaining, state: state)
        } catch let r as ExtractionRejection {
            return r.response
        }
        return try await f(e0, e1, e2, state).intoResponse()
    }
}
